# Generated by Django 3.1.3 on 2022-03-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_auto_20220311_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Об Университете',
                'verbose_name_plural': 'Об Университете',
            },
        ),
        migrations.CreateModel(
            name='Center_carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Центр Карьеры',
                'verbose_name_plural': 'Центр Карьеры',
            },
        ),
        migrations.CreateModel(
            name='Enactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Enactus',
                'verbose_name_plural': 'Enactus',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Студентам',
                'verbose_name_plural': 'Студентам',
            },
        ),
        migrations.AlterModelOptions(
            name='abiturient',
            options={'verbose_name': 'Абитуриентам', 'verbose_name_plural': 'Абитуриентам'},
        ),
        migrations.AlterField(
            model_name='headdis',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturient.header'),
        ),
    ]
